version: '2'
services:
  redis:
    container_name: redis
    image: redis:6
    ports:
      - 6379:6379
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dell_456